name: GitHub Actions Seminar Demo
# to ensure it only runs on pushes to master branch
on: [push]
  # push:
  #   branches:
  #     - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: albonru/seminar_devops2
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}