name: GitHub Actions Seminar Demo
# to ensure it only runs on pushes to master branch
on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v2

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: albonru/seminar_devops2
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


# alternativa: 
    # - name: Docker login
    #   run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    # - name: Build
    #   run: docker build -t backend .
    # - name: Tags
    #   run: |
    #     docker tag front ${{ secrets.DOCKER_USER }}/backend:${{ github.sha }}
    #     docker tag front ${{ secrets.DOCKER_USER }}/backend:latest
    # - name: Push
    #   run: |
    #     docker push ${{ secrets.DOCKER_USER }}/backend:${{ github.sha }}
    #     docker push ${{ secrets.DOCKER_USER }}/backend:latest